# Exported from Render on 2024-04-02T19:09:42Z
services:
- type: web
  name: vibe-gateway
  runtime: docker
  healthCheckPath: /caddyhealth
  region: oregon
  envVars:
  - key: DOWNSTREAM_PORT
    value: 10000
  - key: PORT
    value: 10000
  - key: GATEWAY_USER
    sync: false
  - key: GATEWAY_PASSWORD_HASH
    sync: false
  ipAllowList: &ip-allow-list
  - source: 207.183.181.253
    description: "office network"
- type: web
  name: vibe-gateway-oidc
  branch: oidc
  runtime: docker
  healthCheckPath: /caddyhealth
  region: oregon
  envVars:
  - key: DOWNSTREAM_PORT
    value: 10000
  - key: PORT
    value: 10000
  - key: AUTH0_CLIENT_ID
    sync: false
  - key: AUTH0_CLIENT_SECRET
    sync: false
  - key: AUTH0_DOMAIN
    sync: false
  - key: AUTH0_JWT_SECRET
    sync: false
  ipAllowList: *ip-allow-list
version: "1"
